### ISSUE TITLE
Duplicate Apps That Show Up In Queries (Incomplete, Pre-Reg, No Deposit)

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/brifony#26]
Is there a way that we can set up a checkbox for if an app is a duplicate to remove it from the queries? I think it is good to avoid wasting time by contacting them and this could help us avoid this easily.

**Comment by IshaDakota** [comment]
We had talked about this in the initial meeting - and I pointed out that it was hard because they way REGADMIN presents them is as two different applicants.

We could build a way to mark duplicates - I would estimate this at about 10 hours.

The easiest way to do this using what you already have is to mark the duplicate record as cancelled. This would remove them from those queries. 

NOTE: In all cases, there is a high degree of human error because it is sometimes hard to tell which record is the duplicate. The only failsafe way to dedupe records is to request for BRI to remove the duplicate.
